workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

default:
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud config set project epsilon1-dev
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_CREDS
    - chmod +x ./gitlab_setup_env.sh

build:
  stage: build
  script:
    - ./gitlab_setup_env.sh
    - ls -lah
    - cat .env
    - >
      gcloud builds submit . --tag gcr.io/epsilon1-dev/portal-webclient

deploy:
  stage: deploy
  script:
    - >
      gcloud run deploy portal-webclient --image gcr.io/epsilon1-dev/portal-webclient --platform managed --region us-central1 --allow-unauthenticated
