# Create the .env file based on the secrets provided by gitlab
echo NEXT_PUBLIC_PUBLIC_API_ROOT=$NEXT_PUBLIC_PUBLIC_API_ROOT >> .env
echo NEXT_PUBLIC_WEBPORTAL_API_ROOT=$NEXT_PUBLIC_WEBPORTAL_API_ROOT >> .env
echo NEXT_PUBLIC_SENTIMENT_API_ROOT=$NEXT_PUBLIC_SENTIMENT_API_ROOT >> .env
echo NEXT_PUBLIC_GOOGLE_ANALYTICS=$NEXT_PUBLIC_GOOGLE_ANALYTICS >> .env
