# Create the .env file based on the secrets provided by gitlab
echo NEXT_PUBLIC_PUBLIC_API_ROOT=$NEXT_PUBLIC_PUBLIC_API_ROOT >> .env
echo NEXT_PUBLIC_WEBPORTAL_API_ROOT=$NEXT_PUBLIC_WEBPORTAL_API_ROOT >> .env
echo NEXT_PUBLIC_PIPELINE_API_ROOT=$NEXT_PUBLIC_PIPELINE_API_ROOT >> .env
echo NEXT_PUBLIC_POSTHOG_KEY=$NEXT_PUBLIC_POSTHOG_KEY >> .env
echo NEXT_PUBLIC_PUBLIC_API_V5_ROOT=$NEXT_PUBLIC_PUBLIC_API_V5_ROOT >> .env
echo NEXT_PUBLIC_WEBCLIENT_ROOT=$NEXT_PUBLIC_WEBCLIENT_ROOT >> .env
echo NEXT_PUBLIC_MARK_KEY=$NEXT_PUBLIC_MARK_KEY >> .env
echo NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY >> .env
echo NEXT_PUBLIC_SESSION_TIMEOUT_TIME=$NEXT_PUBLIC_SESSION_TIMEOUT_TIME >> .env